version: "3.0"

services:
  frontend:
    build: frontend-v2
    image: health-care-website-frontend
    container_name: health-care-website-frontend
    networks:
      - health-care-website
    ports:
      - 127.0.0.1:3000:3000

  backend:
    build: backend
    image: health-care-website-backend
    container_name: health-care-website-backend
    volumes:
      - ./backend/instance:/app/instance
      - ./backend/statics:/app/statics
    networks:
      - health-care-website
    ports:
      - 127.0.0.1:5001:5004

networks:
  health-care-website:
    name: health-care-website
