version: '1.0'

services:
  health-care-website-backend-beta:
    build:
      context: .
    ports:
      - "5004:5004"
    volumes:
      - ./instance:/app/instance
      - ./statics:/app/statics
    restart: always
