name: frontend-ci
on:
  push:
    branches:
      - main
      - frontend
      - action
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Resolve Flutter dependency
        run: cd frontend && flutter pub get
      - name: Build web
        run: flutter build web --web-renderer=canvaskit
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-artifact
          path: build/web/
