name: frontend-cd
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deployment
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            if [ -d repo ]; then
              cd repo
              docker compose down
              cd ..
            fi
            git clone https://github.com/${{ github.repository }} repo-tmp --depth=1
            mkdir -p repo
            cp -r repo-tmp/* repo/
            rm -rf repo-tmp
            cd repo
            echo NEXT_PUBLIC_BACKEND_HOST=${{ vars.BACKEND_HOST }} > frontend-v2/.env.local
            docker compose up --build -d
